"""
StudentIQ — Final Exam Marks Predictor
----------------------------------------
A Streamlit web application that loads the pre-trained Linear Regression
model (trained in Student_Final_Marks_Prediction.ipynb) and predicts a
student's Final Exam Marks (out of 100) from five inputs:
Attendance %, Internal Test 1, Internal Test 2, Assignment Score,
and Daily Study Hours.

Run with:  streamlit run app.py
"""

import numpy as np
import pandas as pd
import joblib
import streamlit as st
import matplotlib.pyplot as plt

# ----------------------------------------------------------------------
# Page configuration
# ----------------------------------------------------------------------
st.set_page_config(
    page_title="StudentIQ — Final Marks Predictor",
    page_icon="🎓",
    layout="centered"
)

# ----------------------------------------------------------------------
# Load trained artifacts (model, scaler, feature column order)
# ----------------------------------------------------------------------
@st.cache_resource
def load_artifacts():
    model = joblib.load("final_marks_model.pkl")
    scaler = joblib.load("feature_scaler.pkl")
    feature_columns = joblib.load("feature_columns.pkl")
    return model, scaler, feature_columns

try:
    model, scaler, feature_columns = load_artifacts()
    artifacts_loaded = True
except FileNotFoundError:
    artifacts_loaded = False

# ----------------------------------------------------------------------
# Header
# ----------------------------------------------------------------------
st.title("🎓 StudentIQ: Final Exam Marks Predictor")
st.markdown(
    "This app uses a **Linear Regression** model trained on 2,000 student "
    "records to predict a student's **Final Exam Marks (out of 100)** based "
    "on attendance, internal test scores, assignment performance, and daily "
    "study hours."
)

if not artifacts_loaded:
    st.error(
        "Model files not found. Please make sure `final_marks_model.pkl`, "
        "`feature_scaler.pkl`, and `feature_columns.pkl` are in the same "
        "folder as this app (generated by running the project notebook)."
    )
    st.stop()

st.divider()

# ----------------------------------------------------------------------
# Sidebar — About section
# ----------------------------------------------------------------------
with st.sidebar:
    st.header("About this project")
    st.markdown(
        """
        **Model:** Linear Regression
        **Trained on:** 2,000 student records
        **Test R² Score:** ≈ 0.83
        **Test RMSE:** ≈ 4.6 marks

        **Features used:**
        - Attendance (%)
        - Internal Test 1 (out of 40)
        - Internal Test 2 (out of 40)
        - Assignment Score (out of 10)
        - Daily Study Hours
        """
    )
    st.caption("Built for the Student Academic Performance regression project.")

# ----------------------------------------------------------------------
# Input form
# ----------------------------------------------------------------------
st.subheader("Enter Student Details")

col1, col2 = st.columns(2)

with col1:
    attendance = st.slider("Attendance (%)", min_value=0, max_value=100, value=85)
    test1 = st.slider("Internal Test 1 (out of 40)", min_value=0, max_value=40, value=28)
    test2 = st.slider("Internal Test 2 (out of 40)", min_value=0, max_value=40, value=28)

with col2:
    assignment = st.slider("Assignment Score (out of 10)", min_value=0, max_value=10, value=7)
    study_hours = st.slider("Daily Study Hours", min_value=0, max_value=12, value=3)

predict_btn = st.button("Predict Final Marks", type="primary", use_container_width=True)

# ----------------------------------------------------------------------
# Prediction
# ----------------------------------------------------------------------
if predict_btn:
    input_df = pd.DataFrame(
        [[attendance, test1, test2, assignment, study_hours]],
        columns=feature_columns
    )

    input_scaled = scaler.transform(input_df)
    prediction = model.predict(input_scaled)[0]
    prediction = float(np.clip(prediction, 0, 100))

    st.divider()
    st.subheader("Prediction Result")

    m1, m2 = st.columns(2)
    m1.metric("Predicted Final Exam Marks", f"{prediction:.1f} / 100")

    if prediction >= 75:
        grade_msg = "Excellent 🌟 — well on track for a top grade."
    elif prediction >= 60:
        grade_msg = "Good 👍 — solid performance, room to push higher."
    elif prediction >= 40:
        grade_msg = "Average ⚠️ — consider increasing study hours and attendance."
    else:
        grade_msg = "At Risk 🚨 — significant improvement needed."
    m2.metric("Performance Band", grade_msg.split(" ")[0])

    st.info(grade_msg)

    # Progress bar visualization of predicted marks
    st.progress(min(int(prediction), 100) / 100)

    # ------------------------------------------------------------------
    # Feature contribution chart (standardized coefficient x input value)
    # ------------------------------------------------------------------
    st.subheader("What influenced this prediction?")
    coefficients = model.coef_
    contributions = coefficients * input_scaled[0]

    contrib_df = pd.DataFrame({
        "Feature": feature_columns,
        "Contribution": contributions
    }).sort_values("Contribution", key=abs, ascending=True)

    fig, ax = plt.subplots(figsize=(6, 4))
    colors = ["#d62728" if v < 0 else "#2ca02c" for v in contrib_df["Contribution"]]
    ax.barh(contrib_df["Feature"], contrib_df["Contribution"], color=colors)
    ax.set_xlabel("Contribution to predicted marks")
    ax.axvline(0, color="black", linewidth=0.8)
    fig.tight_layout()
    st.pyplot(fig)

    st.caption(
        "Green bars pushed the prediction up; red bars pulled it down, "
        "relative to an average student in the training data."
    )

st.divider()
st.caption(
    "StudentIQ | Built with Streamlit, scikit-learn, and pandas | "
    "Model: Linear Regression evaluated with MAE, MSE, RMSE, and R²."
)
